# Generated by Django 3.1 on 2020-09-12 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 9, 52, 9, 9817, tzinfo=utc), verbose_name='date_listed'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 9, 52, 9, 10957, tzinfo=utc)),
        ),
    ]
