# Generated by Django 3.1 on 2020-09-12 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200912_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 10, 0, 34, 447753, tzinfo=utc), verbose_name='date_listed'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 10, 0, 34, 448852, tzinfo=utc)),
        ),
    ]
