# Generated by Django 3.1 on 2020-09-12 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200912_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 10, 10, 48, 590897, tzinfo=utc), verbose_name='date_listed'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 10, 10, 48, 592046, tzinfo=utc)),
        ),
    ]
